version: '3'

services:

  laravel:
    build:
      context: ./
      dockerfile: ./docker/laravel/Dockerfile
    container_name: pj_laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - pj-networks

  nginx-laravel:
    build: ./docker/nginx-laravel
    container_name: pj-nginx-laravel
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8880:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - pj-networks

  mysql:
    build: ./docker/mysql
    container_name: pj-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: dungx
      MYSQL_PASSWORD: dungpro123
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - pj-networks

  phpmyadmin:
    build: ./docker/phpmyadmin
    container_name: pj-phpmyadmin
networks:
  pj-networks:
    driver: bridge
volumes:
  data:
